# Utiliser l'image officielle de Node.js comme image de base
FROM node:16

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier le fichier package.json et installer les dépendances
COPY package*.json ./
RUN npm install

# Copier le reste du code source dans le conteneur
COPY . .
# Exposer le port sur lequel l'application s'exécute
EXPOSE 3333